# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240520-143642-dull-phrasing

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    entity_recognition: true
    intent_classification: true
    use_masked_language_model: true
    evaluate_on_number_of_examples: 0
    evaluate_every_number_of_epochs: 10
    checkpoint_model: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 5
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        state_featurizer:
          - name: SingleStateFeaturizer
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        state_featurizer:
          - name: SingleStateFeaturizer
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        state_featurizer:
          - name: SingleStateFeaturizer
